### ISSUE TITLE
Missing subscription information

### ISSUE THREAD

**Issue by mudrd8mz** [rosell/moodle-block_task_oriented_groups#7]
The plugin integrates with an external system. The plugin page provides no relevant information on the conditions of the subscription, no information on how to ontain the API credentials etc.

Reference: https://docs.moodle.org/dev/Plugin_contribution_checklist#Subscription_needed

**Comment by rosell** [comment]
The extension service does not require any subscription or credentials. It is a public service that can be used by anyone. I add this information to the description of the configuration file. I hope that's enough.
